[package]
name = "red"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cstr = "0.2.11"

[lib]
name = "red"
path = "src/red.rs"

[[bin]]
name = "cdefs"
path = "src/cdefs.rs"
